-- GENERATED by scripts/build-setup-sql.mjs — do not edit by hand.
-- Paste this whole file into Supabase → SQL Editor → Run. Safe to re-run.

-- ════════════════ 20260929000000_init.sql ════════════════
-- Architect 2.0 — initial schema. Idempotent: safe to re-run over a partially applied database.
-- Every table has RLS enabled with owner-only policies. `(select auth.uid())` is wrapped in a
-- subselect so Postgres evaluates it once per statement instead of once per row.

-- ── Enums ───────────────────────────────────────────────────────────────────────────────────
do $$ begin create type public.app_mode as enum ('simple', 'pro'); exception when duplicate_object then null; end $$;
do $$ begin create type public.agent_framework as enum ('lyzr', 'langgraph', 'crewai', 'openai-agents', 'custom'); exception when duplicate_object then null; end $$;
do $$ begin create type public.message_role as enum ('user', 'assistant', 'system', 'tool'); exception when duplicate_object then null; end $$;
do $$ begin create type public.deployment_status as enum ('queued', 'building', 'ready', 'error', 'canceled'); exception when duplicate_object then null; end $$;

-- ── Helpers ─────────────────────────────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── profiles ────────────────────────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id             uuid primary key references auth.users (id) on delete cascade,
  username       text,
  avatar_url     text,
  preferred_mode public.app_mode not null default 'simple',
  default_model  text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;

drop policy if exists "profiles: owner can read" on public.profiles;
create policy "profiles: owner can read"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

drop policy if exists "profiles: owner can insert" on public.profiles;
create policy "profiles: owner can insert"
  on public.profiles for insert to authenticated
  with check (id = (select auth.uid()));

drop policy if exists "profiles: owner can update" on public.profiles;
create policy "profiles: owner can update"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- Create a profile row on sign-up, seeded from the GitHub OAuth metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'user_name',
      new.raw_user_meta_data ->> 'preferred_username',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── projects ────────────────────────────────────────────────────────────────────────────────
create table if not exists public.projects (
  id             uuid primary key default gen_random_uuid(),
  owner_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name           text not null check (char_length(name) between 1 and 100),
  description    text,
  framework      public.agent_framework not null default 'lyzr',
  mode           public.app_mode not null default 'simple',
  github_repo    text,
  memory_enabled boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists projects_owner_id_updated_at_idx on public.projects (owner_id, updated_at desc);

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

alter table public.projects enable row level security;

drop policy if exists "projects: owner can read" on public.projects;
create policy "projects: owner can read"
  on public.projects for select to authenticated
  using (owner_id = (select auth.uid()));

drop policy if exists "projects: owner can insert" on public.projects;
create policy "projects: owner can insert"
  on public.projects for insert to authenticated
  with check (owner_id = (select auth.uid()));

drop policy if exists "projects: owner can update" on public.projects;
create policy "projects: owner can update"
  on public.projects for update to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists "projects: owner can delete" on public.projects;
create policy "projects: owner can delete"
  on public.projects for delete to authenticated
  using (owner_id = (select auth.uid()));

-- Child tables are owned through their project.
create or replace function public.owns_project(p_project_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.projects
    where id = p_project_id and owner_id = (select auth.uid())
  );
$$;

-- ── messages ────────────────────────────────────────────────────────────────────────────────
create table if not exists public.messages (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  role       public.message_role not null,
  content    text not null,
  model      text,
  tokens_in  integer check (tokens_in >= 0),
  tokens_out integer check (tokens_out >= 0),
  created_at timestamptz not null default now()
);

create index if not exists messages_project_id_created_at_idx on public.messages (project_id, created_at);

alter table public.messages enable row level security;

drop policy if exists "messages: project owner can read" on public.messages;
create policy "messages: project owner can read"
  on public.messages for select to authenticated
  using (public.owns_project(project_id));

drop policy if exists "messages: project owner can insert" on public.messages;
create policy "messages: project owner can insert"
  on public.messages for insert to authenticated
  with check (public.owns_project(project_id));

drop policy if exists "messages: project owner can delete" on public.messages;
create policy "messages: project owner can delete"
  on public.messages for delete to authenticated
  using (public.owns_project(project_id));

-- ── project_files ───────────────────────────────────────────────────────────────────────────
create table if not exists public.project_files (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  path       text not null check (char_length(path) between 1 and 512),
  content    text not null default '',
  updated_at timestamptz not null default now(),
  unique (project_id, path)
);

drop trigger if exists project_files_set_updated_at on public.project_files;
create trigger project_files_set_updated_at
  before update on public.project_files
  for each row execute function public.set_updated_at();

alter table public.project_files enable row level security;

drop policy if exists "project_files: project owner can read" on public.project_files;
create policy "project_files: project owner can read"
  on public.project_files for select to authenticated
  using (public.owns_project(project_id));

drop policy if exists "project_files: project owner can insert" on public.project_files;
create policy "project_files: project owner can insert"
  on public.project_files for insert to authenticated
  with check (public.owns_project(project_id));

drop policy if exists "project_files: project owner can update" on public.project_files;
create policy "project_files: project owner can update"
  on public.project_files for update to authenticated
  using (public.owns_project(project_id))
  with check (public.owns_project(project_id));

drop policy if exists "project_files: project owner can delete" on public.project_files;
create policy "project_files: project owner can delete"
  on public.project_files for delete to authenticated
  using (public.owns_project(project_id));

-- ── deployments ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.deployments (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  status     public.deployment_status not null default 'queued',
  url        text,
  logs       jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists deployments_project_id_created_at_idx on public.deployments (project_id, created_at desc);

alter table public.deployments enable row level security;

drop policy if exists "deployments: project owner can read" on public.deployments;
create policy "deployments: project owner can read"
  on public.deployments for select to authenticated
  using (public.owns_project(project_id));

drop policy if exists "deployments: project owner can insert" on public.deployments;
create policy "deployments: project owner can insert"
  on public.deployments for insert to authenticated
  with check (public.owns_project(project_id));

drop policy if exists "deployments: project owner can update" on public.deployments;
create policy "deployments: project owner can update"
  on public.deployments for update to authenticated
  using (public.owns_project(project_id))
  with check (public.owns_project(project_id));

-- ════════════════ 20261004000000_profile_google_metadata.sql ════════════════
-- Google sign-in: seed profiles from Google's metadata too (name / picture), not only GitHub's.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'user_name',          -- GitHub
      new.raw_user_meta_data ->> 'preferred_username',
      new.raw_user_meta_data ->> 'full_name',          -- Google
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1)
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'             -- Google
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- ════════════════ 20261005000000_demo_guest_profiles.sql ════════════════
-- Demo mode: anonymous (guest) users have no email or OAuth metadata; name their profile "Guest".
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'user_name',          -- GitHub
      new.raw_user_meta_data ->> 'preferred_username',
      new.raw_user_meta_data ->> 'full_name',          -- Google
      new.raw_user_meta_data ->> 'name',
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Guest'                                          -- anonymous demo users
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- ════════════════ 20261006000000_build_features.sql ════════════════
-- Architect 2.0 — tables for the build loop, memory-driven fixes, GitHub and publishing.
-- Idempotent: safe to re-run. All new tables are owner-only via RLS (directly or via the project).

-- ── projects: plan, agent spec, publishing settings ─────────────────────────────────────────
alter table public.projects add column if not exists plan jsonb;
alter table public.projects add column if not exists agent_spec jsonb;
alter table public.projects add column if not exists plan_status text not null default 'none'
  check (plan_status in ('none', 'draft', 'approved'));
alter table public.projects add column if not exists seo_enabled boolean not null default false;
alter table public.projects add column if not exists cms_enabled boolean not null default false;
alter table public.projects add column if not exists deploy_slug text;

-- ── messages: who pays for this turn (fair-billing ledger) and what kind of turn it was ─────
alter table public.messages add column if not exists billed_to text not null default 'user'
  check (billed_to in ('user', 'agent'));
alter table public.messages add column if not exists kind text not null default 'chat'
  check (kind in ('chat', 'plan', 'build', 'fix'));

-- ── project_files: keep the previous version so Pro mode can show a diff ────────────────────
alter table public.project_files add column if not exists previous_content text;
alter table public.project_files add column if not exists updated_by text not null default 'agent'
  check (updated_by in ('agent', 'user'));

-- ── run_events: the agent trace + logs (plan, recall, tool, file, error, fix, deploy) ───────
create table if not exists public.run_events (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  run_id     uuid not null,
  kind       text not null check (kind in ('plan', 'recall', 'tool', 'file', 'error', 'fix', 'deploy', 'log', 'check')),
  title      text not null,
  detail     jsonb not null default '{}'::jsonb,
  tokens_in  integer check (tokens_in >= 0),
  tokens_out integer check (tokens_out >= 0),
  created_at timestamptz not null default now()
);
create index if not exists run_events_project_created_idx on public.run_events (project_id, created_at desc);
alter table public.run_events enable row level security;
drop policy if exists "run_events: project owner can read" on public.run_events;
create policy "run_events: project owner can read" on public.run_events for select to authenticated
  using (public.owns_project(project_id));
drop policy if exists "run_events: project owner can insert" on public.run_events;
create policy "run_events: project owner can insert" on public.run_events for insert to authenticated
  with check (public.owns_project(project_id));

-- ── fix_attempts: fix memory + loop breaker ─────────────────────────────────────────────────
-- error_signature is a normalized fingerprint of the error so the same failure is recognised
-- across sessions and projects (the user's own history), not just within one chat.
create table if not exists public.fix_attempts (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid not null references public.projects (id) on delete cascade,
  owner_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  error_signature text not null,
  error_message   text not null,
  attempt         integer not null check (attempt >= 1),
  fix_summary     text not null,
  outcome         text not null default 'pending' check (outcome in ('pending', 'succeeded', 'failed', 'rolled_back')),
  tokens          integer not null default 0,
  created_at      timestamptz not null default now()
);
create index if not exists fix_attempts_owner_sig_idx on public.fix_attempts (owner_id, error_signature, created_at desc);
alter table public.fix_attempts enable row level security;
drop policy if exists "fix_attempts: owner can read" on public.fix_attempts;
create policy "fix_attempts: owner can read" on public.fix_attempts for select to authenticated
  using (owner_id = (select auth.uid()));
drop policy if exists "fix_attempts: owner can insert" on public.fix_attempts;
create policy "fix_attempts: owner can insert" on public.fix_attempts for insert to authenticated
  with check (owner_id = (select auth.uid()) and public.owns_project(project_id));
drop policy if exists "fix_attempts: owner can update" on public.fix_attempts;
create policy "fix_attempts: owner can update" on public.fix_attempts for update to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

-- ── decisions: the project's decision log (shown in the Memory tab, injected every turn) ────
create table if not exists public.decisions (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  text       text not null check (char_length(text) between 1 and 500),
  source     text not null default 'plan' check (source in ('plan', 'chat', 'user', 'fix')),
  created_at timestamptz not null default now()
);
create index if not exists decisions_project_idx on public.decisions (project_id, created_at);
alter table public.decisions enable row level security;
drop policy if exists "decisions: project owner can read" on public.decisions;
create policy "decisions: project owner can read" on public.decisions for select to authenticated
  using (public.owns_project(project_id));
drop policy if exists "decisions: project owner can write" on public.decisions;
create policy "decisions: project owner can write" on public.decisions for all to authenticated
  using (public.owns_project(project_id)) with check (public.owns_project(project_id));

-- ── github_connections: the user's GitHub token, encrypted by the app (AES-256-GCM) ─────────
create table if not exists public.github_connections (
  user_id          uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  login            text,
  token_ciphertext text not null,
  scopes           text,
  updated_at       timestamptz not null default now()
);
alter table public.github_connections enable row level security;
drop policy if exists "github_connections: owner only" on public.github_connections;
create policy "github_connections: owner only" on public.github_connections for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- ── cms_entries: content mode for public sites ──────────────────────────────────────────────
create table if not exists public.cms_entries (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  collection text not null check (collection in ('pages', 'posts', 'faqs')),
  slug       text not null,
  title      text not null,
  body       text not null default '',
  status     text not null default 'draft' check (status in ('draft', 'published')),
  updated_at timestamptz not null default now(),
  unique (project_id, collection, slug)
);
alter table public.cms_entries enable row level security;
drop policy if exists "cms_entries: project owner only" on public.cms_entries;
create policy "cms_entries: project owner only" on public.cms_entries for all to authenticated
  using (public.owns_project(project_id)) with check (public.owns_project(project_id));

-- ── deployments: publish results ────────────────────────────────────────────────────────────
alter table public.deployments add column if not exists seo_score integer;
alter table public.deployments add column if not exists security_findings jsonb not null default '[]'::jsonb;
drop policy if exists "deployments: project owner can delete" on public.deployments;
create policy "deployments: project owner can delete" on public.deployments for delete to authenticated
  using (public.owns_project(project_id));

-- Let the API see new tables/columns immediately.
notify pgrst, 'reload schema';
